steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: serverless-sql
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/gblaquiere-dev/public/serverless-sql', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    dir: serverless-db-proxy
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/gblaquiere-dev/public/serverless-db-proxy', '.' ]
  - name: 'gcr.io/cloud-builders/go'
    entrypoint: "/bin/sh"
    dir: serverless-db-proxy
    args:
      - -c
      - |
        GOARCH=amd64 GOOS=windows CGO_ENABLED=0 go build -o win64/serverless-db-proxy.exe main.go
        GOARCH=amd64 GOOS=linux CGO_ENABLED=0 go build -o linux64/serverless-db-proxy main.go
        GOARCH=amd64 GOOS=darwin CGO_ENABLED=0 go build -o darwin64/serverless-db-proxy main.go
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: "/bin/sh"
    dir: serverless-db-proxy
    args:
      - -c
      - |
        gsutil -h 'Content-Disposition:filename=serverless-db-proxy.exe' cp win64/serverless-db-proxy.exe gs://serverless-db-proxy/win64/
        gsutil -h 'Content-Disposition:filename=serverless-db-proxy'  cp linux64/serverless-db-proxy gs://serverless-db-proxy/linux64/
        gsutil -h 'Content-Disposition:filename=serverless-db-proxy'  cp darwin64/serverless-db-proxy gs://serverless-db-proxy/darwin64/
        gsutil -h 'Content-Disposition:filename=startup.sh' cp startup.sh gs://serverless-db-proxy/
images: ['us-central1-docker.pkg.dev/gblaquiere-dev/public/serverless-sql',
        'us-central1-docker.pkg.dev/gblaquiere-dev/public/serverless-db-proxy']
